# Generated by Django 5.2.3 on 2025-07-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0001_initial'),
        ('skills', '0002_alter_addskills_availability_alter_addskills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skills.addskills'),
        ),
    ]
