# Generated by Django 5.2.3 on 2025-07-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_rename_submitted_at_contactmessage_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
