# Generated by Django 5.2.3 on 2025-07-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_rename_created_at_contactmessage_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
