# Generated by Django 5.2.3 on 2025-07-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('OT', 'Other')], default='OT', max_length=2)),
                ('availability', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('average_rating', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('OT', 'Other')], default='OT', max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.userprofile')),
            ],
        ),
    ]
