# Generated by Django 5.2 on 2025-07-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('HI', 'Home Improvement'), ('HB', 'Health & Beauty'), ('OT', 'Other')], default='OT', max_length=2)),
                ('availability', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('average_rating', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('HI', 'Home Improvement'), ('HB', 'Health & Beauty'), ('OT', 'Other')], default='OT', max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.userprofile')),
            ],
        ),
    ]
