# Generated by Django 5.2.3 on 2025-07-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('HI', 'Home Improvement'), ('HB', 'Health & Beauty'), ('OT', 'Other')], default='OT', max_length=2)),
                ('availability', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('average_rating', models.FloatField(default=0.0)),
                ('slug', models.SlugField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOffer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('HI', 'Home Improvement'), ('HB', 'Health & Beauty'), ('OT', 'Other')], default='OT', max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
