# Generated by Django 5.2 on 2025-07-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addskills',
            name='profilePic',
        ),
    ]
