# Generated by Django 5.2 on 2025-07-16 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOffer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReq', to=settings.AUTH_USER_MODEL),
        ),
    ]
