# Generated by Django 5.2 on 2025-07-14 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_addskills_profilepic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='addskills',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='addskills',
            name='availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addskills',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RequestSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('OT', 'Other')], default='OT', max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
