# Generated by Django 5.2.3 on 2025-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_addskills_slug_alter_addskills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addskills',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
