# Generated by Django 5.2 on 2025-07-15 15:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_username_addskills_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addskills',
            name='date',
        ),
        migrations.AddField(
            model_name='addskills',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestskills',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 15, 15, 41, 37, 860897, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
