# Generated by Django 5.2 on 2025-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_remove_addskills_date_addskills_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addskills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestskills',
            name='user',
        ),
        migrations.AlterField(
            model_name='addskills',
            name='category',
            field=models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('HI', 'Home Improvement'), ('HB', 'Health & Beauty'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='requestskills',
            name='category',
            field=models.CharField(choices=[('TC', 'Technical'), ('CR', 'Crafts'), ('LN', 'Languages'), ('HI', 'Home Improvement'), ('HB', 'Health & Beauty'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
