# Generated by Django 5.2 on 2025-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_addskills_user_remove_requestskills_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestskills',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addskills',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestskills',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
