# Generated by Django 5.2 on 2025-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_requestskills_title_alter_addskills_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestskills',
            name='title',
            field=models.CharField(default='No Title2', max_length=100),
            preserve_default=False,
        ),
    ]
